# Generated by Django 4.2.23 on 2025-08-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdownlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsOptionsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Subjects',
                'verbose_name_plural': 'Subjects Lists',
            },
        ),
        migrations.AlterModelOptions(
            name='classoptionsmodel',
            options={'verbose_name': 'Class List', 'verbose_name_plural': 'Class Lists'},
        ),
        migrations.AlterModelOptions(
            name='districtsoptionsmodel',
            options={'verbose_name': 'District List', 'verbose_name_plural': 'District Lists'},
        ),
        migrations.AlterModelOptions(
            name='stateoptionsmodel',
            options={'verbose_name': 'State List', 'verbose_name_plural': 'State Lists'},
        ),
    ]
