# Generated by Django 4.2.23 on 2025-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdownlists', '0002_subjectsoptionsmodels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollNumberOptionsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Roll Number',
            },
        ),
    ]
