# Generated by Django 4.2.23 on 2025-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdownlists', '0003_rollnumberoptionsmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollnumberoptionsmodels',
            name='roll_number',
            field=models.CharField(max_length=5),
        ),
    ]
