# Generated by Django 4.2.23 on 2025-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdownlists', '0004_alter_rollnumberoptionsmodels_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicOptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Academic Session',
            },
        ),
    ]
