# Generated by Django 4.2.23 on 2025-08-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropdownlists', '0005_academicoptionsmodel'),
        ('studentsapp', '0010_alter_studentmodel_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstExamMarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(blank=True, null=True)),
                ('english_i', models.IntegerField(blank=True, null=True)),
                ('english_ii', models.IntegerField(blank=True, null=True)),
                ('hindi', models.IntegerField(blank=True, null=True)),
                ('sanskrit', models.IntegerField(blank=True, null=True)),
                ('social_studies', models.IntegerField(blank=True, null=True)),
                ('moral_science', models.IntegerField(blank=True, null=True)),
                ('general_knowledge', models.IntegerField(blank=True, null=True)),
                ('physics', models.IntegerField(blank=True, null=True)),
                ('chemistry', models.IntegerField(blank=True, null=True)),
                ('biology', models.IntegerField(blank=True, null=True)),
                ('mathematics', models.IntegerField(blank=True, null=True)),
                ('computer', models.IntegerField(blank=True, null=True)),
                ('drawing', models.IntegerField(blank=True, null=True)),
                ('handwriting', models.IntegerField(blank=True, null=True)),
                ('conversation', models.IntegerField(blank=True, null=True)),
                ('rhymes', models.IntegerField(blank=True, null=True)),
                ('environmental_studies', models.IntegerField(blank=True, null=True)),
                ('english_hindi_reading', models.IntegerField(blank=True, null=True)),
                ('history', models.IntegerField(blank=True, null=True)),
                ('geography', models.IntegerField(blank=True, null=True)),
                ('supw', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdownlists.classoptionsmodel')),
                ('roll_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdownlists.rollnumberoptionsmodels')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsapp.studentmodel')),
            ],
        ),
    ]
