# Generated by Django 4.2.23 on 2025-08-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstexammarksmodel',
            name='class_name',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'Class 1'), ('II', 'Class 2'), ('III', 'Class 3'), ('IV', 'Class 4'), ('V', 'Class 5'), ('VI', 'Class 6'), ('VII', 'Class 7'), ('VIII', 'Class 8'), ('IX', 'Class 9'), ('X', 'Class 10')], max_length=20),
        ),
    ]
