# Generated by Django 4.2.23 on 2025-08-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0003_firstexammarksmodel_academic_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstexammarksmodel',
            name='days_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstexammarksmodel',
            name='first_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstexammarksmodel',
            name='my_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstexammarksmodel',
            name='working_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
