# Generated by Django 4.2.23 on 2025-08-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0004_alter_firstexammarksmodel_days_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstexammarksmodel',
            name='academic_session',
            field=models.CharField(choices=[('2024-25', '2024-25'), ('2025-26', '2025-26')], max_length=10),
        ),
    ]
