# Generated by Django 4.2.23 on 2025-08-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0005_alter_firstexammarksmodel_academic_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstexammarksmodel',
            name='terminal_exam',
            field=models.CharField(blank=True, choices=[('first', 'First Terminal'), ('second', 'Second Terminal'), ('third', 'Third Terminal')], max_length=6, null=True),
        ),
    ]
