# Generated by Django 4.2.23 on 2025-08-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0006_firstexammarksmodel_terminal_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstexammarksmodel',
            name='terminal_exam',
            field=models.CharField(choices=[('first', 'First Terminal'), ('second', 'Second Terminal'), ('third', 'Third Terminal')], max_length=6),
        ),
    ]
