# Generated by Django 4.2.23 on 2025-08-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0014_alter_studentmodel_academic_session'),
        ('dropdownlists', '0005_academicoptionsmodel'),
        ('resultapp', '0007_alter_firstexammarksmodel_terminal_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstExamMarksModel',
            new_name='TerminalExamMarksModel',
        ),
    ]
