# Generated by Django 4.2.23 on 2025-08-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0008_rename_firstexammarksmodel_terminalexammarksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalexammarksmodel',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminalexammarksmodel',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
