# Generated by Django 4.2.23 on 2025-08-23 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0009_terminalexammarksmodel_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminalexammarksmodel',
            old_name='english_i',
            new_name='english_language',
        ),
    ]
