# Generated by Django 4.2.23 on 2025-08-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0010_rename_english_i_terminalexammarksmodel_english_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminalexammarksmodel',
            old_name='english_ii',
            new_name='english_literature',
        ),
    ]
