# Generated by Django 4.2.23 on 2025-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0011_rename_english_ii_terminalexammarksmodel_english_literature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
