# Generated by Django 4.2.23 on 2025-08-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0013_terminalexammarksmodel_final_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalexammarksmodel',
            name='science',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
