# Generated by Django 4.2.23 on 2025-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0015_alter_terminalexammarksmodel_final_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
