# Generated by Django 4.2.23 on 2025-08-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0017_alter_terminalexammarksmodel_final_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='drawing',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='handwriting',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
