# Generated by Django 4.2.23 on 2025-08-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0018_alter_terminalexammarksmodel_drawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='english_hindi_reading',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
