# Generated by Django 4.2.23 on 2025-08-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0019_alter_terminalexammarksmodel_english_hindi_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminalexammarksmodel',
            old_name='english_hindi_reading',
            new_name='reading',
        ),
    ]
