# Generated by Django 4.2.23 on 2025-08-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0020_rename_english_hindi_reading_terminalexammarksmodel_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalexammarksmodel',
            name='spelling',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
