# Generated by Django 4.2.23 on 2025-08-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0021_terminalexammarksmodel_spelling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalexammarksmodel',
            name='spelling',
        ),
    ]
