# Generated by Django 4.2.23 on 2025-08-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0022_remove_terminalexammarksmodel_spelling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='biology',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='chemistry',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='computer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='conversation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='english',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='english_language',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='english_literature',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='environmental_studies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='general_knowledge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='geography',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='hindi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='history',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='mathematics',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='moral_science',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='physics',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='rhymes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='sanskrit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='science',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='social_studies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
