# Generated by Django 4.2.23 on 2025-08-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0023_alter_terminalexammarksmodel_biology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='history',
            field=models.IntegerField(default=0),
        ),
    ]
