# Generated by Django 4.2.23 on 2025-08-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0024_alter_terminalexammarksmodel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='biology',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='computer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='conversation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='environmental_studies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='geography',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='mathematics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='rhymes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='science',
            field=models.IntegerField(default=0),
        ),
    ]
