# Generated by Django 4.2.23 on 2025-08-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0025_alter_terminalexammarksmodel_biology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='english_language',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='english_literature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='general_knowledge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='hindi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='moral_science',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='sanskrit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='social_studies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
