# Generated by Django 4.2.23 on 2025-08-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0026_alter_terminalexammarksmodel_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalexammarksmodel',
            name='dictation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminalexammarksmodel',
            name='spelling',
            field=models.IntegerField(default=0),
        ),
    ]
