# Generated by Django 4.2.23 on 2025-08-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0027_terminalexammarksmodel_dictation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
