# Generated by Django 4.2.23 on 2025-08-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0028_alter_terminalexammarksmodel_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalexammarksmodel',
            name='correction_status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=10, null=True),
        ),
    ]
