# Generated by Django 4.2.23 on 2025-08-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0031_alter_terminalexammarksmodel_correction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalexammarksmodel',
            name='correction_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Printed', 'Printed'), ('Error', 'ERROR')], default='Pending', max_length=10),
        ),
    ]
