# Generated by Django 4.2.23 on 2025-08-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropdownlists', '0004_alter_rollnumberoptionsmodels_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(blank=True, max_length=10)),
                ('student_name', models.CharField(max_length=150)),
                ('academic_session', models.CharField(default='2025-26', max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('class_name', models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'Class 1'), ('II', 'Class 2'), ('III', 'Class 3'), ('IV', 'Class 4'), ('V', 'Class 5'), ('VI', 'Class 6'), ('VII', 'Class 7'), ('VIII', 'Class 8'), ('IX', 'Class 9'), ('X', 'Class 10')], max_length=50, null=True)),
                ('section_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2)),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True, max_length=300)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('mobile_no', models.BigIntegerField(blank=True, null=True)),
                ('aadhar_no', models.BigIntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdownlists.districtsoptionsmodel')),
                ('roll_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdownlists.rollnumberoptionsmodels')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdownlists.stateoptionsmodel')),
            ],
            options={
                'verbose_name': 'Students Detail',
            },
        ),
    ]
