# Generated by Django 4.2.23 on 2025-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='conveyance',
            field=models.CharField(blank=True, choices=[('bus', 'BUS'), ('self', 'SELF')], max_length=5, null=True),
        ),
    ]
