# Generated by Django 4.2.23 on 2025-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_studentmodel_conveyance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='whatsapp_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
