# Generated by Django 4.2.23 on 2025-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0003_studentmodel_whatsapp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='academic_session',
            field=models.CharField(blank=True, default='2025-26', max_length=10, null=True),
        ),
    ]
