# Generated by Django 4.2.23 on 2025-08-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdownlists', '0005_academicoptionsmodel'),
        ('studentsapp', '0006_alter_studentmodel_academic_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdownlists.academicoptionsmodel'),
        ),
    ]
