# Generated by Django 4.2.23 on 2025-08-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdownlists', '0005_academicoptionsmodel'),
        ('studentsapp', '0009_alter_studentmodel_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdownlists.rollnumberoptionsmodels'),
        ),
    ]
