# Generated by Django 4.2.23 on 2025-08-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0010_alter_studentmodel_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='academic_session',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='2025-26', max_length=10, null=True),
        ),
    ]
