# Generated by Django 4.2.23 on 2025-08-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0013_alter_studentmodel_academic_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='academic_session',
            field=models.CharField(choices=[('2024-25', '2024-25'), ('2025-26', '2025-26')], max_length=10),
        ),
    ]
