# Generated by Django 4.2.23 on 2025-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0014_alter_studentmodel_academic_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
